-- PostgreSQL version of the Flux banking schema.
-- Create the database from psql if needed:
--   CREATE DATABASE flux;
-- Then connect to it and run this file.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_cuenta_enum') THEN
    CREATE TYPE tipo_cuenta_enum AS ENUM ('debito', 'credito', 'ahorro');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_transaccion_enum') THEN
    CREATE TYPE tipo_transaccion_enum AS ENUM (
      'retiro',
      'deposito',
      'transferencia_entrada',
      'transferencia_salida'
    );
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS sucursal (
  id_sucursal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  global_id UUID NOT NULL DEFAULT gen_random_uuid(),
  nombre VARCHAR(255) NOT NULL,
  localidad VARCHAR(255) NOT NULL,
  region VARCHAR(120) NOT NULL,
  nodo_origen VARCHAR(120) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT sucursal_global_id_unico UNIQUE (global_id)
);

CREATE TABLE IF NOT EXISTS cliente (
  id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  global_id UUID NOT NULL DEFAULT gen_random_uuid(),
  nombre VARCHAR(120) NOT NULL,
  ap_pat VARCHAR(120) NOT NULL DEFAULT '',
  ap_mat VARCHAR(120),
  direccion VARCHAR(255),
  sucursal_alta_id INTEGER NOT NULL,
  region VARCHAR(120) NOT NULL,
  nodo_origen VARCHAR(120) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT cliente_global_id_unico UNIQUE (global_id),
  CONSTRAINT cliente_sucursal_alta
    FOREIGN KEY (sucursal_alta_id)
    REFERENCES sucursal(id_sucursal)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS cuenta (
  id_cuenta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  global_id UUID NOT NULL DEFAULT gen_random_uuid(),
  id_sucursal INTEGER NOT NULL,
  numero_cuenta VARCHAR(20) NOT NULL,
  tipo_cuenta tipo_cuenta_enum NOT NULL DEFAULT 'debito',
  saldo NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  fecha_creacion DATE NOT NULL DEFAULT CURRENT_DATE,
  region VARCHAR(120) NOT NULL,
  nodo_origen VARCHAR(120) NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  sincronizado BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT cuenta_numero_unico UNIQUE (numero_cuenta),
  CONSTRAINT cuenta_global_id_unico UNIQUE (global_id),
  CONSTRAINT cuenta_saldo_no_negativo CHECK (saldo >= 0),
  CONSTRAINT cuenta_pertenece_sucursal
    FOREIGN KEY (id_sucursal)
    REFERENCES sucursal(id_sucursal)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS tarjeta (
  id_tarjeta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  global_id UUID NOT NULL DEFAULT gen_random_uuid(),
  id_cuenta INTEGER NOT NULL,
  numero_tarjeta VARCHAR(16) NOT NULL,
  nip INTEGER NOT NULL,
  fecha_expiracion DATE NOT NULL,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  sucursal_id INTEGER NOT NULL,
  region VARCHAR(120) NOT NULL,
  nodo_origen VARCHAR(120) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT tarjeta_numero_unico UNIQUE (numero_tarjeta),
  CONSTRAINT tarjeta_global_id_unico UNIQUE (global_id),
  CONSTRAINT tarjeta_vinculada_cuenta
    FOREIGN KEY (id_cuenta)
    REFERENCES cuenta(id_cuenta)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT tarjeta_sucursal
    FOREIGN KEY (sucursal_id)
    REFERENCES sucursal(id_sucursal)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS cliente_cuenta (
  id_cliente INTEGER NOT NULL,
  id_cuenta INTEGER NOT NULL,
  rol VARCHAR(30) NOT NULL DEFAULT 'titular',
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (id_cliente, id_cuenta),

  CONSTRAINT clientecuenta_apunta_cliente
    FOREIGN KEY (id_cliente)
    REFERENCES cliente(id_cliente)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT clientecuenta_apunta_cuenta
    FOREIGN KEY (id_cuenta)
    REFERENCES cuenta(id_cuenta)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS transaccion (
  id_transaccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  global_id UUID NOT NULL DEFAULT gen_random_uuid(),
  id_cuenta INTEGER NOT NULL,
  tipo tipo_transaccion_enum NOT NULL,
  monto NUMERIC(12,2) NOT NULL,
  saldo_resultante NUMERIC(12,2) NOT NULL,
  cuenta_origen VARCHAR(20),
  cuenta_destino VARCHAR(20),
  concepto VARCHAR(140),
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  hora TIME NOT NULL DEFAULT CURRENT_TIME,
  token VARCHAR(64),
  sucursal_id INTEGER NOT NULL,
  region VARCHAR(120) NOT NULL,
  nodo_origen VARCHAR(120) NOT NULL,
  sincronizado BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT transaccion_global_id_unico UNIQUE (global_id),
  CONSTRAINT transaccion_pertenece_cuenta
    FOREIGN KEY (id_cuenta)
    REFERENCES cuenta(id_cuenta)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT transaccion_sucursal
    FOREIGN KEY (sucursal_id)
    REFERENCES sucursal(id_sucursal)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT transaccion_monto_positivo CHECK (monto > 0)
);

ALTER TABLE transaccion
  ADD COLUMN IF NOT EXISTS concepto VARCHAR(140);

CREATE INDEX IF NOT EXISTS idx_cliente_sucursal_region
  ON cliente (sucursal_alta_id, region);

CREATE INDEX IF NOT EXISTS idx_cuenta_sucursal_region
  ON cuenta (id_sucursal, region);

CREATE INDEX IF NOT EXISTS idx_cuenta_nodo_sincronizado
  ON cuenta (nodo_origen, sincronizado);

CREATE INDEX IF NOT EXISTS idx_transaccion_cuenta_fecha
  ON transaccion (id_cuenta, fecha DESC, hora DESC);

CREATE INDEX IF NOT EXISTS idx_transaccion_nodo_sincronizado
  ON transaccion (nodo_origen, sincronizado);

CREATE INDEX IF NOT EXISTS idx_tarjeta_login
  ON tarjeta (numero_tarjeta, nip)
  WHERE activa = TRUE;

CREATE TABLE IF NOT EXISTS sesion_cuenta (
  numero_cuenta VARCHAR(20) PRIMARY KEY,
  session_token UUID NOT NULL,
  id_sucursal INTEGER NOT NULL,
  region VARCHAR(120) NOT NULL,
  nodo_origen VARCHAR(120) NOT NULL,
  nombre_sucursal VARCHAR(255) NOT NULL,
  abierta_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expira_en TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sesion_cuenta_expira_en
  ON sesion_cuenta (expira_en);

CREATE OR REPLACE FUNCTION set_actualizado_en()
RETURNS TRIGGER AS $$
BEGIN
  NEW.actualizado_en = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sucursal_actualizado_en ON sucursal;
CREATE TRIGGER trg_sucursal_actualizado_en
BEFORE UPDATE ON sucursal
FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

DROP TRIGGER IF EXISTS trg_cliente_actualizado_en ON cliente;
CREATE TRIGGER trg_cliente_actualizado_en
BEFORE UPDATE ON cliente
FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

DROP TRIGGER IF EXISTS trg_cuenta_actualizado_en ON cuenta;
CREATE TRIGGER trg_cuenta_actualizado_en
BEFORE UPDATE ON cuenta
FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();

DROP TRIGGER IF EXISTS trg_tarjeta_actualizado_en ON tarjeta;
CREATE TRIGGER trg_tarjeta_actualizado_en
BEFORE UPDATE ON tarjeta
FOR EACH ROW EXECUTE FUNCTION set_actualizado_en();
